/**
 * Interface (Contract) for Plagiarism and AI Detection.
 * Implementations must adhere to this contract.
 */
class PlagiarismDetectorGateway {
    /**
     * Checks the probability of the text being generated by AI.
     * @param {string} text 
     * @returns {Promise<number>} Score 0-100
     */
    async checkAiProbability(text) {
      throw new Error('Method checkAiProbability() must be implemented');
    }
  
    /**
     * Checks for plagiarism in the text.
     * @param {string} text 
     * @param {string} title 
     * @returns {Promise<{score: number, reportUrl: string, sources: Array, matches: Array}>}
     */
    async checkPlagiarism(text, title) {
      throw new Error('Method checkPlagiarism() must be implemented');
    }
  
    /**
     * Checks references for hallucinations.
     * @param {string} referencesText 
     * @returns {Promise<Array>}
     */
    async checkReferences(referencesText) {
      throw new Error('Method checkReferences() must be implemented');
    }
  }
  
  module.exports = PlagiarismDetectorGateway;
  